spring:
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    datasource:
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://35.239.48.56:week4
            username: root
            password: "ds.earth"
